baseURL = "https://bal.tips/"
languageCode = "en-us"
title = "Ballerina Coding Tips"

theme = "docdock"
enableGitInfo = true
copyright = "Â© Hasitha Aravinda"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[params]
custom_css = ["css/tips-theme.css", "css/tips.css","css/variant-teal.css"]
custom_js = ["js/tips-theme.js"]
themeStyle = "original"
highlightStyle = "friendly"

[taxonomies]
tags = 'tags'

[markup.highlight]
codeFences = false